# Generated by Django 5.1.1 on 2024-09-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_user_category_parent_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='SKU',
        ),
    ]
