# Generated by Django 5.1.1 on 2024-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SKU',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
